---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: "kube-system"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: armando-ramirez.vila@capgemini.com
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the DNS-01 challenge provider
    dns01:
      providers:
      - name: route53
        route53:
          hostedZoneID: CLUSTER_ZONE_ID
          accessKeyID: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: route53-config
            key: secret-access-key
          region: eu-west-1
